/* =============================================================
   YOUR MILESTONES LIVE HERE — this is the only file you edit.
   Add new entries at the BOTTOM of the list (newest last).

   Copy this template, paste it just above the closing ]; and
   fill it in:

   {
     title: 'What you achieved',
     date: '23 Jul 2026',            // day is optional: 'Jul 2026' works too
     category: 'LLMs',               // any short label you like
     description: 'One or two sentences about what you did and learned.',
     skills: ['Skill A', 'Skill B'], // [] if none
     resources: [                    // [] if none
       'artifact or file name',      // plain string = reference note
       { label: 'GitHub repo', url: 'https://github.com/...' }, // object = link
     ],
     cvWorthy: false,                // true = gold ★ CV-worthy badge
   },

   Optional per entry: status: 'done' | 'progress' | 'planned' — adds a
   status pill ('planned' renders dimmed). Omitted = plain milestone.
   ============================================================= */

window.CONFIG = {
  accentColor: '#8B6CFF', // designer options: '#8B6CFF' | '#FF6B4A' | '#2FD6A0' | '#FF4D9D'
  newestFirst: false,     // true = show the latest milestone at the top
};

window.MILESTONES = [
  {
    title: 'AI assistants as shortcuts',
    date: '2025 - Jan 2026',
    category: 'Foundations',
    description: 'Used Copilot, Gemini and ChatGPT as day-to-day shortcuts for generating code, answering technical questions, rewriting communication and accelerating individual development tasks. At this stage, AI was mainly a faster assistant rather than part of a structured engineering workflow.',
    skills: ['GitHub Copilot', 'Gemini', 'ChatGPT', 'Prompting'],
    resources: [],
    cvWorthy: false,
  },
  {
    title: 'Context-aware AI engineering',
    date: 'Jan 2026 - Apr 2026',
    category: 'Context Engineering',
    description: 'Moved from isolated prompts to context-aware AI work by giving agents real repository, architecture and business context. Used this approach while driving a large cards refactor covering broad and deeply connected parts of the application, which reached testing with only two reported bugs.',
    skills: [
      'Context engineering',
      'Repository context',
      'Architecture reasoning',
      'AI-assisted refactoring',
    ],
    resources: [],
    cvWorthy: true,
  },
  {
    title: 'Project context tree',
    date: 'Jan 2026 - Mar 2026',
    category: 'Context Engineering',
    description: 'Structured project knowledge as a context tree so AI agents could understand modules, business journeys, architectural decisions and relationships between components. This was created before adopting reusable agent skills.',
    skills: [
      'Context trees',
      'Project documentation',
      'Agent context management',
      'Knowledge structuring',
    ],
    resources: ['Neo-Agent-Context.md'],
    cvWorthy: false,
  },
  {
    title: 'AI and Developer Productivity course',
    date: 'Mar 15, 2026',
    category: 'Learning',
    description: 'Completed the AI and Developer Productivity course, covering practical applications of artificial intelligence in software development and developer productivity.',
    skills: [
      'AI software development',
      'Developer productivity',
      'Artificial intelligence',
    ],
    resources: ['AI and Developer Productivity certificate'],
    cvWorthy: true,
  },
  {
    title: 'Discovery of agent skills',
    date: 'Late Mar 2026',
    category: 'Skills & Plugins',
    description: 'Discovered the agent skill concept and began moving beyond large context files toward reusable, focused instructions that agents could load only when a specific workflow was required.',
    skills: [
      'Agent skills',
      'Progressive disclosure',
      'Reusable workflows',
      'Context efficiency',
    ],
    resources: [],
    cvWorthy: false,
  },
  {
    title: 'Agentic coding toolchain',
    date: 'Apr 2026 - Present',
    category: 'Agentic Coding',
    description: 'Expanded from individual AI assistants into an agentic coding toolchain involving ChatGPT, Codex, Claude Code, Cursor, Copilot and Gemini. Began selecting tools according to autonomy, planning quality, code-review capability, context handling and suitability for different engineering tasks.',
    skills: [
      'Claude Code',
      'Codex',
      'Cursor',
      'GitHub Copilot',
      'Gemini',
      'Agent selection',
    ],
    resources: [],
    cvWorthy: false,
  },
  {
    title: 'Cursor-based agent workflows',
    date: 'Apr 2026 - May 2026',
    category: 'Agentic Coding',
    description: 'Used Cursor Pro for repository-aware coding, custom-agent experimentation, automated bug handling, documentation generation, testing workflows and multi-repository agent automation.',
    skills: [
      'Cursor',
      'Custom agents',
      'Repository automation',
      'AI-assisted coding',
    ],
    resources: [],
    cvWorthy: false,
  },
  {
    title: 'Claude Code adoption',
    date: 'Jun 2026 - Present',
    category: 'Agentic Coding',
    description: 'Adopted Claude Pro and Claude Code as core engineering tools. Practised CLAUDE.md project initialization, file-based context, plan mode, implementation mode, terminal workflows, documentation lookup and repository-level development.',
    skills: [
      'Claude Code',
      'CLAUDE.md',
      'Plan mode',
      'Repository context',
      'Terminal workflows',
    ],
    resources: ['Claude Pro', 'Claude Code'],
    cvWorthy: false,
  },
  {
    title: 'Claude skills and plugins course',
    date: 'Jun 29, 2026',
    category: 'Learning',
    description: 'Completed the Udemy course Claude - Master Claude Cowork, Claude Code, Skills & Plugins, strengthening practical knowledge of Claude Code, skills, plugins and agent-based workflows.',
    skills: [
      'Claude Code',
      'Claude Cowork',
      'Agent skills',
      'Plugins',
      'AI workflows',
    ],
    resources: [
      'Claude - Master Claude Cowork, Claude Code, Skills & Plugins',
    ],
    cvWorthy: true,
  },
  {
    title: 'Company engineering harness contribution',
    date: 'Jun 2026 - Present',
    category: 'Engineering Harness',
    description: 'Contributed to improving the engineering harness used at CoorB and Neo by building reusable agent skills, commands, scripts and contextual workflows for Android engineering, Figma review and localization.',
    skills: [
      'Engineering harnesses',
      'Agent skills',
      'Commands',
      'Automation scripts',
      'Workflow design',
    ],
    resources: ['CoorB engineering harness', 'Neo Android repository'],
    cvWorthy: true,
  },
  {
    title: 'Android Figma extractor refactor',
    date: 'Jun 2026',
    category: 'Design Automation',
    description: 'Revamped the Android Figma design extractor into a generic, reusable and ledger-first workflow. Reduced the main agent body from roughly 298 lines to about 104 lines and moved approximately 210 lines of detailed guidance into four focused reference files.',
    skills: [
      'Figma automation',
      'Android UI',
      'Agent refactoring',
      'Progressive disclosure',
      'Design tokens',
    ],
    resources: ['android-figma-design-extractor'],
    cvWorthy: true,
  },
  {
    title: 'Ledger-first Figma extraction',
    date: 'Jun 2026',
    category: 'Design Automation',
    description: 'Introduced a ledger-only operating mode for extracting structured Figma information before implementation. The workflow standardized token rules, asset handling, string extraction and build-ready design brief generation.',
    skills: [
      'Design ledgers',
      'Figma inspection',
      'Token mapping',
      'Asset workflows',
      'Implementation briefs',
    ],
    resources: ['android-figma-design-extractor'],
    cvWorthy: true,
  },
  {
    title: 'Platform-agnostic Figma Design QA skill',
    date: 'Jun 2026',
    category: 'Design Automation',
    description: 'Created a platform-agnostic Figma Design QA skill that reviews designs before code implementation. It identifies Arabic and English inconsistencies, legacy tokens, missing tokens, unmappable values and other designer-side issues.',
    skills: [
      'Figma Design QA',
      'Design systems',
      'Localization QA',
      'Token validation',
      'Pre-development review',
    ],
    resources: ['figma-design-qa'],
    cvWorthy: true,
  },
  {
    title: 'Approval-gated Figma comments',
    date: 'Jun 2026',
    category: 'Design Automation',
    description: 'Added support for posting review feedback directly to Figma through MCP. The workflow uses multiple approval gates to prevent an agent from publishing comments without explicit confirmation.',
    skills: [
      'Figma MCP',
      'Human-in-the-loop workflows',
      'Approval gates',
      'Design collaboration',
    ],
    resources: ['figma-design-qa', 'Figma MCP pull request'],
    cvWorthy: true,
  },
  {
    title: 'Android code-versus-Figma comparison skill',
    date: 'Jun 2026',
    category: 'Design Automation',
    description: 'Created a read-only skill that compares Android XML or Jetpack Compose implementations against Figma. It produces separate reports for designer-side issues and code-versus-design mismatches.',
    skills: [
      'Android',
      'Jetpack Compose',
      'XML layouts',
      'Figma comparison',
      'Visual QA',
    ],
    resources: ['android-figma-comparison'],
    cvWorthy: true,
  },
  {
    title: 'Design QA integration into feature development',
    date: 'Jun 2026',
    category: 'Engineering Harness',
    description: 'Added a non-blocking hint to the Android new-feature workflow so engineers are reminded to run design QA when a Figma design is available, without forcing the workflow to stop.',
    skills: [
      'Developer experience',
      'Workflow integration',
      'Quality gates',
      'Android feature development',
    ],
    resources: ['Android new-feature flow'],
    cvWorthy: true,
  },
  {
    title: 'Neo Android translations plugin',
    date: 'Jun 2026 - Jul 2026',
    category: 'Localization Automation',
    description: 'Created the coorb-neo-android plugin to centralize and automate translation workflows for the Neo Android project.',
    skills: [
      'Plugin development',
      'Android localization',
      'Workflow automation',
      'Repository tooling',
    ],
    resources: ['coorb-neo-android'],
    cvWorthy: true,
  },
  {
    title: 'Neo translations skill',
    date: 'Jun 2026 - Jul 2026',
    category: 'Localization Automation',
    description: 'Built a local-first translation skill with target-branch validation, duplicate detection, Arabic and Hindi drafting, Babelish synchronization and merge-request creation.',
    skills: [
      'Localization',
      'Arabic translation',
      'Hindi translation',
      'Babelish',
      'Git workflows',
      'Validation gates',
    ],
    resources: ['neo-translations'],
    cvWorthy: true,
  },
  {
    title: 'Translation environment setup skill',
    date: 'Jun 2026 - Jul 2026',
    category: 'Localization Automation',
    description: 'Created a setup and repair skill that checks whether the translation environment is correctly configured and fixes missing or invalid setup requirements.',
    skills: [
      'Environment validation',
      'Automated setup',
      'Developer tooling',
      'Error recovery',
    ],
    resources: ['neo-translations-setup'],
    cvWorthy: true,
  },
  {
    title: 'Translation commands and read-only agent',
    date: 'Jun 2026 - Jul 2026',
    category: 'Localization Automation',
    description: 'Added reusable translation commands and a read-only extraction agent. The workflow includes setup, string addition, string updates and a ledger-oriented agent for inspecting translation data without modifying it.',
    skills: [
      'Slash commands',
      'Read-only agents',
      'Translation extraction',
      'Ledger workflows',
    ],
    resources: [
      '/setup-translations',
      '/add-strings',
      '/update-strings',
      'translation-extractor',
    ],
    cvWorthy: true,
  },
  {
    title: 'Translation automation scripts',
    date: 'Jun 2026 - Jul 2026',
    category: 'Localization Automation',
    description: 'Implemented scripts for environment checking, repository setup, CSV retrieval, translation search, CSV validation, local Android string generation and merge-request creation.',
    skills: [
      'Scripting',
      'CSV validation',
      'Android resources',
      'Git automation',
      'Translation pipelines',
    ],
    resources: [
      'check-setup',
      'setup_repo',
      'fetch_csv',
      'search_strings',
      'validate_csv',
      'generate_local_strings',
      'create_mr',
    ],
    cvWorthy: true,
  },
  {
    title: 'Skills, commands and sub-agent architecture',
    date: 'Jun 2026 - Present',
    category: 'Agent Architecture',
    description: 'Developed a clear model for separating persistent project rules, reusable skills, explicit commands and specialized sub-agents. Evaluated when to use plan mode, skill-based workflows and brainstorming gates without creating conflicting instructions.',
    skills: [
      'Agent architecture',
      'Skills',
      'Commands',
      'Sub-agents',
      'Plan mode',
      'Workflow gates',
    ],
    resources: ['Superpowers skills framework'],
    cvWorthy: false,
  },
  {
    title: 'Skill-writing and review methodology',
    date: 'Jun 2026 - Present',
    category: 'Skills & Plugins',
    description: 'Studied and applied skill-writing methodology and review rules, including progressive disclosure, concise descriptions, avoiding duplicated examples and converting real evaluation failures into explicit workflow rules.',
    skills: [
      'Skill authoring',
      'Skill review',
      'Progressive disclosure',
      'Agent evaluation',
      'Instruction design',
    ],
    resources: ['Superpowers writing-skills'],
    cvWorthy: false,
  },
  {
    title: 'Multi-agent engineering workflow',
    date: 'Jul 2026 - Present',
    category: 'Agent Orchestration',
    description: 'Started structuring engineering workflows that assign different tasks to Claude, Codex and Copilot according to their strengths, instead of expecting one agent to handle planning, implementation, review and validation equally well.',
    skills: [
      'Multi-agent systems',
      'Task delegation',
      'Claude',
      'Codex',
      'Copilot',
      'Model selection',
    ],
    resources: [],
    cvWorthy: false,
  },
  {
    title: 'AI-assisted Android practice system',
    date: 'Jul 2026',
    category: 'Continuous Learning',
    description: 'Established a twice-weekly practical learning routine focused on AI-assisted Android engineering with ChatGPT, Cursor, Claude Code and Copilot. The routine covers prompting, code review, Figma QA and translation workflows with exercises and reusable prompt patterns.',
    skills: [
      'AI-assisted Android',
      'Prompt engineering',
      'Code review',
      'Figma QA',
      'Translation workflows',
    ],
    resources: ['Twice-weekly AI engineering practice'],
    cvWorthy: false,
  },
  {
    title: 'Automation engines and AI agents',
    date: 'Jul 2026',
    category: 'Automation & MCP',
    description: 'Built a practical understanding of the difference between an automation engine, an AI agent and an external model. Explored how n8n acts as an orchestration backend while agents perform reasoning and tools or MCP servers provide actions and data access.',
    skills: [
      'n8n',
      'Automation engines',
      'AI agents',
      'MCP',
      'Workflow orchestration',
    ],
    resources: ['n8n trial workspace'],
    cvWorthy: false,
  },
  {
    title: 'Notion as an AI knowledge layer',
    date: 'Jul 2026',
    category: 'Personal AI Systems',
    description: 'Adopted Notion Plus and Notion AI and positioned Notion as the knowledge and planning layer for a personal Life OS supported by AI agents.',
    skills: [
      'Notion AI',
      'Knowledge management',
      'Personal operating systems',
      'Agent context',
    ],
    resources: ['Notion Plus', 'Notion AI', 'Life OS template'],
    cvWorthy: false,
  },
  {
    title: 'Life OS master-agent design',
    date: 'Jul 18, 2026',
    category: 'Personal AI Systems',
    description: 'Designed a Life OS master agent with Notion as the planning layer. The design covers course planning, work planning, daily and weekly planning, reviews, replanning, startup behaviour and confirmation requirements before making changes.',
    skills: [
      'Master-agent design',
      'Notion',
      'Planning systems',
      'Human approval',
      'Replanning',
    ],
    resources: ['Life OS master-agent design'],
    cvWorthy: false,
  },
  {
    title: 'Life OS implementation plan',
    date: 'Jul 18, 2026',
    category: 'Personal AI Systems',
    description: 'Created an implementation plan for the Life OS agent with verified Notion mappings, seven operating modes, confirmation-gated writes, Todoist as the execution layer and evaluation scenarios for planning and replanning workflows.',
    skills: [
      'Agent implementation planning',
      'Notion integration',
      'Todoist integration',
      'Evaluation scenarios',
      'Confirmation gates',
    ],
    resources: ['Life OS master-agent implementation plan'],
    cvWorthy: false,
  },
  {
    title: 'ReadCraft plugin definition',
    date: 'Jul 21, 2026',
    category: 'Product Building',
    description: 'Defined the ReadCraft plugin around two core capabilities: reviewing skills and plugins with technical improvement suggestions, and helping humans understand and review complex English skill files more easily.',
    skills: [
      'Plugin design',
      'Skill review',
      'Human-readable explanations',
      'Technical analysis',
      'Instruction transformation',
    ],
    resources: ['Superpowers writing-skills'],
    cvWorthy: false,
  },
  {
    title: 'From AI user to AI workflow builder',
    date: '2025 - Present',
    category: 'Journey',
    description: 'Progressed from using AI for individual shortcuts to building context-aware workflows, reusable skills, engineering harnesses, design and localization automation, multi-agent systems and structured AI product concepts.',
    skills: [
      'AI-assisted engineering',
      'Context engineering',
      'Agent skills',
      'Plugin development',
      'Agent orchestration',
      'AI product design',
    ],
    resources: [],
    cvWorthy: true,
  },
];
